// Generated by gencpp from file xarm_vision/CallPickPlaceDemoRequest.msg
// DO NOT EDIT!


#ifndef XARM_VISION_MESSAGE_CALLPICKPLACEDEMOREQUEST_H
#define XARM_VISION_MESSAGE_CALLPICKPLACEDEMOREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Empty.h>

namespace xarm_vision
{
template <class ContainerAllocator>
struct CallPickPlaceDemoRequest_
{
  typedef CallPickPlaceDemoRequest_<ContainerAllocator> Type;

  CallPickPlaceDemoRequest_()
    : call()  {
    }
  CallPickPlaceDemoRequest_(const ContainerAllocator& _alloc)
    : call(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Empty_<ContainerAllocator>  _call_type;
  _call_type call;





  typedef boost::shared_ptr< ::xarm_vision::CallPickPlaceDemoRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::xarm_vision::CallPickPlaceDemoRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CallPickPlaceDemoRequest_

typedef ::xarm_vision::CallPickPlaceDemoRequest_<std::allocator<void> > CallPickPlaceDemoRequest;

typedef boost::shared_ptr< ::xarm_vision::CallPickPlaceDemoRequest > CallPickPlaceDemoRequestPtr;
typedef boost::shared_ptr< ::xarm_vision::CallPickPlaceDemoRequest const> CallPickPlaceDemoRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::xarm_vision::CallPickPlaceDemoRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::xarm_vision::CallPickPlaceDemoRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::xarm_vision::CallPickPlaceDemoRequest_<ContainerAllocator1> & lhs, const ::xarm_vision::CallPickPlaceDemoRequest_<ContainerAllocator2> & rhs)
{
  return lhs.call == rhs.call;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::xarm_vision::CallPickPlaceDemoRequest_<ContainerAllocator1> & lhs, const ::xarm_vision::CallPickPlaceDemoRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace xarm_vision

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::xarm_vision::CallPickPlaceDemoRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xarm_vision::CallPickPlaceDemoRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xarm_vision::CallPickPlaceDemoRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xarm_vision::CallPickPlaceDemoRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xarm_vision::CallPickPlaceDemoRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xarm_vision::CallPickPlaceDemoRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::xarm_vision::CallPickPlaceDemoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "22a4d46e3805f1c07152518d635b48f3";
  }

  static const char* value(const ::xarm_vision::CallPickPlaceDemoRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x22a4d46e3805f1c0ULL;
  static const uint64_t static_value2 = 0x7152518d635b48f3ULL;
};

template<class ContainerAllocator>
struct DataType< ::xarm_vision::CallPickPlaceDemoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "xarm_vision/CallPickPlaceDemoRequest";
  }

  static const char* value(const ::xarm_vision::CallPickPlaceDemoRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::xarm_vision::CallPickPlaceDemoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Empty call\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Empty\n"
;
  }

  static const char* value(const ::xarm_vision::CallPickPlaceDemoRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::xarm_vision::CallPickPlaceDemoRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.call);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CallPickPlaceDemoRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::xarm_vision::CallPickPlaceDemoRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::xarm_vision::CallPickPlaceDemoRequest_<ContainerAllocator>& v)
  {
    s << indent << "call: ";
    s << std::endl;
    Printer< ::std_msgs::Empty_<ContainerAllocator> >::stream(s, indent + "  ", v.call);
  }
};

} // namespace message_operations
} // namespace ros

#endif // XARM_VISION_MESSAGE_CALLPICKPLACEDEMOREQUEST_H
