(cl:defpackage xarm_vision-srv
  (:use )
  (:export
   "CALLPICKPLACEDEMO"
   "<CALLPICKPLACEDEMO-REQUEST>"
   "CALLPICKPLACEDEMO-REQUEST"
   "<CALLPICKPLACEDEMO-RESPONSE>"
   "CALLPICKPLACEDEMO-RESPONSE"
  ))

